# Generated by Django 3.0.4 on 2020-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='net', max_length=100)),
                ('network_type', models.CharField(default='vlan', max_length=100)),
                ('physical_network', models.CharField(default='public', max_length=100)),
                ('tenant_id', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
