# Generated by Django 3.0.4 on 2020-03-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edgetron', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Edgetron',
        ),
    ]
