# Generated by Django 3.0.4 on 2020-03-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgetron', '0002_auto_20200326_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='net', max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Edgetron',
        ),
    ]
